export const actionNames = {
  LOAD: {
    LOADGAME: "loadGame",
    NEWGAME: "newGame",
  },
  DISPLAY: {
    BRIGHTNESS_ID: "brightness",
    TRAILS_ID: "trails",
    SUBTITLES_ID: "subtitles",
    WIDESCREEN_ID: "widescreen",
    RADAR_ID: "radar",
    HUD_ID: "hud",
    SCREENPOS_ID: "screenpos",
    CHANGING_POS: "changingpos",
    RADAR_MAPBLIPS: 0,
    RADAR_BLIPSONLY: 1,
    RADAR_OFF: 2,
  },
  CONTROLS: {
    CONFIG_ID: "config",
    MODE_ID: "mode",
    VIB_ID: "vibration",
    FP_ID: "firstperson",
    
    MODE_CAR: 0,
    MODE_FOOT: 1,

    CONFIG_1: 0,
    CONFIG_2: 1,
    CONFIG_3: 2,
    CONFIG_4: 3,
  },
  MAP: {
    LEGEND_ID: "legend",
    ZOOM: "mapZoom",
    PAN_X: "mapPanX",
    PAN_Y: "mapPanY",
  },
  AUDIO: {
    SFX_ID: "sfx",
    MUSIC_ID: "music",
    RADIO_ID: "radio",
    OUTPUT_ID: "output",

    RADIO_FLASH: 0,
    RADIO_KCHAT: 1,
    RADIO_FEVER: 2,
    RADIO_VROCK: 3,
    RADIO_VCPR: 4,
    RADIO_ESPANTOSO: 5,
    RADIO_EMOTION: 6,
    RADIO_WAVE: 7,
    RADIO_WILDSTYLE: 8,
    RADIO_DELMUNDO: 9, // Hi Talal

    RADIO_LIST_START: 0,
    RADIO_LIST_END: 8,
  },
  ARROWS: {
    DIRECTION_RIGHT: -1,
    DIRECTION_LEFT: -2,
    DIRECTION_UP: -3,
    DIRECTION_DOWN: -4,
    DIRECTION_UP_RIGHT: -5,
    DIRECTION_UP_LEFT: -6,
    DIRECTION_DOWN_RIGHT: -7,
    DIRECTION_DOWN_LEFT: -8,
  },
  GENERAL: {
    SELECT: 0,
    HOVER: 1,
    BACK: 2,
    SPECIAL: 3,
  },
};
