export const menuStrings = {
    en: {
      menu: {
        map: "Map",
        brief: "Brief",
        load: "Load",
        stats: "Stats",
        controls: "Controls",
        audio: "Audio",
        display: "Display",
        language: "Language",
        credits: "Credits",
      },
      brief: {
        intro: [
          "Go get some sleep.",
          "What are you gonna do?",
          "I'll drop by your office tomorrow and we can start sorting this mess out."
        ],
        hotel: [
          "But because it's you, because we got history, I'm gonna let you handle this.",
          "Look, Sonny, you got my word.",
          "I'll be in touch."
        ]
      },
      language: {
        english: "English",
        french: "French",
        german: "German",
        italian: "Italian",
        spanish: "Spanish",
      },
      load: {
        loadgame: "Load Game",
        newgame: "New Game",
        savefile: "Save File",
        notpresent: "Not Present",
        jan: "Jan",
        feb: "Feb",
        mar: "Mar",
        apr: "Apr",
        may: "May",
        jun: "Jun",
        jul: "Jul",
        aug: "Aug",
        sep: "Sep",
        oct: "Oct",
        nov: "Nov",
        dec: "Dec",
      },
      stats: {
        percentage: "Percentage completed",
        attempts: "Mission attempts",
        playtime: "Playing Time",
        dayspassed: "Days passed in game",
        safehouse: "Safehouse visits",
        rampages: "Rampages passed",
        hidden: "Hidden Packages found",
        youwasted: "People you've wasted",
        otherswasted: "People wasted by others",
        carsdestroyed: "Road Vehicles destroyed",
        boatsdestroyed: "Boats destroyed",
        aircraftdestroyed: "Planes & Helicopters destroyed",
        tires: "Tires popped with gunfire",
        starsattained: "Total number of wanted stars attained",
        starsevaded: "Total number of wanted stars evaded",
        busted: "Times busted",
        wasted: "Hospital visits",
        headshots: "Number of headshots",
        dailyspending: "Daily police spending",
        criminals: "Criminals wasted",
        explosives: "Kgs of explosives used",
        fired: "Bullets fired",
        hit: "Bullets hit",
        accuracy: "Accuracy",
        foot: "Dist. traveled on foot [miles]",
        car: "Dist. traveled by car [miles]",
        bike: "Dist. traveled by bike [miles]",
        boat: "Dist. traveled by boat [miles]",
        golf: "Dist. traveled by golf cart [miles]",
        heli: "Dist. traveled by helicopter [miles]",
        totaldistance: "Total distance traveled [miles]",
        maxdist: "Max. INSANE Jump dist. [m]",
        maxheight: "Max. INSANE Jump height. [m]",
        maxflip: "Max. INSANE Jump flips",
        unique: "Unique Jumps completed",
        maxrotation: "Max. INSANE Jump rotation",
        bestinsane: "Best INSANE stunt so far:",
        noinsane: "No INSANE strunts completed",
        wheelietime: "Longest Wheelie time [secs]",
        wheeliedist: "Longest Wheelie distance [m]",
        stoppietime: "Longest Stoppie time [secs]",
        stoppiedist: "Longest Stoppie distance [m]",
        twowheeltime: "Longest 2 wheels time [secs]",
        twowheeldist: "Longest 2 wheels distance [m]",
        criminals_v: "Criminals killed on Vigilante Mission",
        vigilante: "Highest Vigilante Mission level",
        passengers: "Passengers dropped off",
        taxicash: "Cash made in taxi",
        peoplesaved: "People saved in an Ambulance",
        paramedic: "Highest Paramedic Mission level",
        fires: "Total fires extinguished",
        firetruck: "Fire Truck Mission level",
        stores: "Stores Knocked Off",
        assassination: "Assassination Contracts Completed",
        flight: "Flight hours",
        fish: "Fishes fed",
        mostfavorite: "Most Favorite Radio Station",
        leastfavorite: "Least Favorite Radio Station",
        sprayings: "Sprayings",
        weapon: "Weapon Budget",
        fashion: "Fashion Budget",
        property: "Property Budget",
        paynspray: "Auto Repair and Painting Budget",
        destroyed: "Property Destroyed",
        media: "Highest media attention",
        ignored: "Ignored",
        outof: " out of "
      }
    },
    es: {
      menu: {
        map: "Mapa",
        brief: "Informe",
        load: "Cargar",
        stats: "Estadísticas",
        controls: "Controles",
        audio: "Sonido",
        display: "Pantalla",
        language: "Idioma",
        credits: "Créditos",
      },
      language: {
        english: "Inglés",
        french: "Francés",
        german: "Alemán",
        italian: "Italiano",
        spanish: "Español",
      },
      brief: {
        intro: [
          "Vete a dormir un poco.",
          "¯Quž es lo que vas a hacer?",
          "Ma®ana te dejarž en tu oficina y podremos empezar a solucionar toda este desorden."
        ],
        hotel: [
          "But because it's you, because we got history, I'm gonna let you handle this.",
          "Look, Sonny, you got my word.",
          "I'll be in touch."
        ],
      },
      load: {
        loadgame: "Cargar partida",
        newgame: "Nueva partida",
        savefile: "No hay archivo",
        notpresent: "guardado",
        jan: "Ene",
        feb: "Feb",
        mar: "Mar",
        apr: "Abr",
        may: "May",
        jun: "Jun",
        jul: "Jul",
        aug: "Ago",
        sep: "Sep",
        oct: "Oct",
        nov: "Nov",
        dec: "Dic",
      },
      stats: {
        percentage: "Percentage completed",
        attempts: "Mission attempts",
        playtime: "Playing Time",
        dayspassed: "Days passed in game",
        safehouse: "Safehouse visits",
        rampages: "Rampages passed",
        hidden: "Hidden Packages found",
        youwasted: "People you've wasted",
        otherswasted: "People wasted by others",
        carsdestroyed: "Road Vehicles destroyed",
        boatsdestroyed: "Boats destroyed",
        aircraftdestroyed: "Planes & Helicopters destroyed",
        tires: "Tires popped with gunfire",
        starsattained: "Total number of wanted stars attained",
        starsevaded: "Total number of wanted stars evaded",
        busted: "Times busted",
        wasted: "Hospital visits",
        headshots: "Number of headshots",
        dailyspending: "Daily police spending",
        criminals: "Criminals wasted",
        explosives: "Kgs of explosives used",
        fired: "Bullets fired",
        hit: "Bullets hit",
        accuracy: "Accuracy",
        foot: "Dist. traveled on foot [miles]",
        car: "Dist. traveled by car [miles]",
        bike: "Dist. traveled by bike [miles]",
        boat: "Dist. traveled by boat [miles]",
        golf: "Dist. traveled by golf cart [miles]",
        heli: "Dist. traveled by helicopter [miles]",
        totaldistance: "Total distance traveled [miles]",
        maxdist: "Max. INSANE Jump dist. [m]",
        maxheight: "Max. INSANE Jump height. [m]",
        maxflip: "Max. INSANE Jump flips",
        unique: "Unique Jumps completed",
        maxrotation: "Max. INSANE Jump rotation",
        bestinsane: "Best INSANE stunt so far",
        noinsane: "No INSANE strunts completed",
        wheelietime: "Longest Wheelie time [secs]",
        wheeliedist: "Longest Wheelie distance [m]",
        stoppietime: "Longest Stoppie time [secs]",
        stoppiedist: "Longest Stoppie distance [m]",
        twowheeltime: "Longest 2 wheels time [secs]",
        twowheeldist: "Longest 2 wheels distance [m]",
        criminals_v: "Criminals killed on Vigilante Mission",
        vigilante: "Highest Vigilante Mission level",
        passengers: "Passengers dropped off",
        taxicash: "Cash made in taxi",
        peoplesaved: "People saved in an Ambulance",
        paramedic: "Highest Paramedic Mission level",
        fires: "Total fires extinguished",
        firetruck: "Fire Truck Mission level",
        stores: "Stores Knocked Off",
        assassination: "Assassination Contracts Completed",
        flight: "Flight hours",
        fish: "Fishes fed",
        mostfavorite: "Most Favorite Radio Station",
        leastfavorite: "Least Favorite Radio Station",
        sprayings: "Sprayings",
        weapon: "Weapon Budget",
        fashion: "Fashion Budget",
        property: "Property Budget",
        paynspray: "Auto Repair and Painting Budget",
        destroyed: "Property Destroyed",
        media: "Highest media attention",
        ignored: "Ignored",
        outof: " out of "
      }
    },
    fr: {
      menu: {
        map: "Carte",
        brief: "Briefing",
        load: "Charger",
        stats: "Statistiques",
        controls: "Commandes",
        audio: "Audio",
        display: "Affichage",
        language: "Langue",
        credits: "Crédits",
      },
      language: {
        english: "Anglais",
        french: "Français",
        german: "Allemand",
        italian: "Italien",
        spanish: "Espagnol",
      },
      brief: {
        intro: [
          "Va roupiller.",
          "Qu'est-ce que tu vas faire?",
          "Je passerai — ton bureau demain et on essayera de trouver une solution — ce merdier."
        ],
        hotel: [
          "But because it's you, because we got history, I'm gonna let you handle this.",
          "Look, Sonny, you got my word.",
          "I'll be in touch."
        ],
      },
      load: {
        loadgame: "Charger partie",
        newgame: "Nouvelle partie",
        savefile: "Pas de sauvegarde",
        notpresent: "",
        jan: "Jan",
        feb: "Fev",
        mar: "Mar",
        apr: "Avr",
        may: "Mai",
        jun: "Jun",
        jul: "Jui",
        aug: "Ao",
        sep: "Sept",
        oct: "Oct",
        nov: "Nov",
        dec: "Dec",
      },
      stats: {
        percentage: "Percentage completed",
        attempts: "Mission attempts",
        playtime: "Playing Time",
        dayspassed: "Days passed in game",
        safehouse: "Safehouse visits",
        rampages: "Rampages passed",
        hidden: "Hidden Packages found",
        youwasted: "People you've wasted",
        otherswasted: "People wasted by others",
        carsdestroyed: "Road Vehicles destroyed",
        boatsdestroyed: "Boats destroyed",
        aircraftdestroyed: "Planes & Helicopters destroyed",
        tires: "Tires popped with gunfire",
        starsattained: "Total number of wanted stars attained",
        starsevaded: "Total number of wanted stars evaded",
        busted: "Times busted",
        wasted: "Hospital visits",
        headshots: "Number of headshots",
        dailyspending: "Daily police spending",
        criminals: "Criminals wasted",
        explosives: "Kgs of explosives used",
        fired: "Bullets fired",
        hit: "Bullets hit",
        accuracy: "Accuracy",
        foot: "Dist. traveled on foot [miles]",
        car: "Dist. traveled by car [miles]",
        bike: "Dist. traveled by bike [miles]",
        boat: "Dist. traveled by boat [miles]",
        golf: "Dist. traveled by golf cart [miles]",
        heli: "Dist. traveled by helicopter [miles]",
        totaldistance: "Total distance traveled [miles]",
        maxdist: "Max. INSANE Jump dist. [m]",
        maxheight: "Max. INSANE Jump height. [m]",
        maxflip: "Max. INSANE Jump flips",
        unique: "Unique Jumps completed",
        maxrotation: "Max. INSANE Jump rotation",
        bestinsane: "Best INSANE stunt so far",
        noinsane: "No INSANE strunts completed",
        wheelietime: "Longest Wheelie time [secs]",
        wheeliedist: "Longest Wheelie distance [m]",
        stoppietime: "Longest Stoppie time [secs]",
        stoppiedist: "Longest Stoppie distance [m]",
        twowheeltime: "Longest 2 wheels time [secs]",
        twowheeldist: "Longest 2 wheels distance [m]",
        criminals_v: "Criminals killed on Vigilante Mission",
        vigilante: "Highest Vigilante Mission level",
        passengers: "Passengers dropped off",
        taxicash: "Cash made in taxi",
        peoplesaved: "People saved in an Ambulance",
        paramedic: "Highest Paramedic Mission level",
        fires: "Total fires extinguished",
        firetruck: "Fire Truck Mission level",
        stores: "Stores Knocked Off",
        assassination: "Assassination Contracts Completed",
        flight: "Flight hours",
        fish: "Fishes fed",
        mostfavorite: "Most Favorite Radio Station",
        leastfavorite: "Least Favorite Radio Station",
        sprayings: "Sprayings",
        weapon: "Weapon Budget",
        fashion: "Fashion Budget",
        property: "Property Budget",
        paynspray: "Auto Repair and Painting Budget",
        destroyed: "Property Destroyed",
        media: "Highest media attention",
        ignored: "Ignored",
        outof: " out of "
      }
    },
    de: {
      menu: {
        map: "Karte",
        brief: "Missionsinfo",
        load: "Laden",
        stats: "Statistiken",
        controls: "Steuerung",
        audio: "Audio",
        display: "Anzeige",
        language: "Sprache",
        credits: "Credits",
      },
      language: {
        english: "Englisch",
        french: "Französisch",
        german: "Deutsch",
        italian: "Italienisch",
        spanish: "Spanisch",
      },
      brief: {
        intro: [
          "Leg dich schlafen.",
          "Was hast du vor?",
          "Ich komme morgen zu dir ins B¬ro, dann sehen wir weiter."
        ],
        hotel: [
          "But because it's you, because we got history, I'm gonna let you handle this.",
          "Look, Sonny, you got my word.",
          "I'll be in touch."
        ],
      },
      load: {
        loadgame: "Spiel laden",
        newgame: "Neues Spiel",
        savefile: "Datei",
        notpresent: "nicht vorhanden",
        jan: "Jan",
        feb: "Feb",
        mar: "Mar",
        apr: "Apr",
        may: "Mai",
        jun: "Jun",
        jul: "Jul",
        aug: "Aug",
        sep: "Sept",
        oct: "Okt",
        nov: "Nov",
        dec: "Dez",
      },
      stats: {
        percentage: "Percentage completed",
        attempts: "Mission attempts",
        playtime: "Playing Time",
        dayspassed: "Days passed in game",
        safehouse: "Safehouse visits",
        rampages: "Rampages passed",
        hidden: "Hidden Packages found",
        youwasted: "People you've wasted",
        otherswasted: "People wasted by others",
        carsdestroyed: "Road Vehicles destroyed",
        boatsdestroyed: "Boats destroyed",
        aircraftdestroyed: "Planes & Helicopters destroyed",
        tires: "Tires popped with gunfire",
        starsattained: "Total number of wanted stars attained",
        starsevaded: "Total number of wanted stars evaded",
        busted: "Times busted",
        wasted: "Hospital visits",
        headshots: "Number of headshots",
        dailyspending: "Daily police spending",
        criminals: "Criminals wasted",
        explosives: "Kgs of explosives used",
        fired: "Bullets fired",
        hit: "Bullets hit",
        accuracy: "Accuracy",
        foot: "Dist. traveled on foot [miles]",
        car: "Dist. traveled by car [miles]",
        bike: "Dist. traveled by bike [miles]",
        boat: "Dist. traveled by boat [miles]",
        golf: "Dist. traveled by golf cart [miles]",
        heli: "Dist. traveled by helicopter [miles]",
        totaldistance: "Total distance traveled [miles]",
        maxdist: "Max. INSANE Jump dist. [m]",
        maxheight: "Max. INSANE Jump height. [m]",
        maxflip: "Max. INSANE Jump flips",
        unique: "Unique Jumps completed",
        maxrotation: "Max. INSANE Jump rotation",
        bestinsane: "Best INSANE stunt so far",
        noinsane: "No INSANE strunts completed",
        wheelietime: "Longest Wheelie time [secs]",
        wheeliedist: "Longest Wheelie distance [m]",
        stoppietime: "Longest Stoppie time [secs]",
        stoppiedist: "Longest Stoppie distance [m]",
        twowheeltime: "Longest 2 wheels time [secs]",
        twowheeldist: "Longest 2 wheels distance [m]",
        criminals_v: "Criminals killed on Vigilante Mission",
        vigilante: "Highest Vigilante Mission level",
        passengers: "Passengers dropped off",
        taxicash: "Cash made in taxi",
        peoplesaved: "People saved in an Ambulance",
        paramedic: "Highest Paramedic Mission level",
        fires: "Total fires extinguished",
        firetruck: "Fire Truck Mission level",
        stores: "Stores Knocked Off",
        assassination: "Assassination Contracts Completed",
        flight: "Flight hours",
        fish: "Fishes fed",
        mostfavorite: "Most Favorite Radio Station",
        leastfavorite: "Least Favorite Radio Station",
        sprayings: "Sprayings",
        weapon: "Weapon Budget",
        fashion: "Fashion Budget",
        property: "Property Budget",
        paynspray: "Auto Repair and Painting Budget",
        destroyed: "Property Destroyed",
        media: "Highest media attention",
        ignored: "Ignored",
        outof: " out of "
      }
    },
    it: {
      menu: {
        map: "Mappa",
        brief: "Briefing",
        load: "Carica",
        stats: "Statistiche",
        controls: "Comandi",
        audio: "Audio",
        display: "Video",
        language: "Lingua",
        credits: "Crediti",
      },
      language: {
        english: "Inglese",
        french: "Francese",
        german: "Tedesco",
        italian: "Italiano",
        spanish: "Spagnolo",
      },
      brief: {
        intro: [
          "Vai a riposarti.",
          "Che cosa intendi fare?",
          "Passer¥ domani a trovarti in ufficio e troveremo un modo per risolvere questo casino."
        ],
        hotel: [
          "But because it's you, because we got history, I'm gonna let you handle this.",
          "Look, Sonny, you got my word.",
          "I'll be in touch."
        ],
      },
      load: {
        loadgame: "Carica partita",
        newgame: "Nuova partita",
        savefile: "Salvataggio",
        notpresent: "non trovato",
        jan: "Gen",
        feb: "Feb",
        mar: "Mar",
        apr: "Apr",
        may: "Mag",
        jun: "Giu",
        jul: "Lug",
        aug: "Ago",
        sep: "Set",
        oct: "Ott",
        nov: "Nov",
        dec: "Dic",
      },
      stats: {
        percentage: "Percentage completed",
        attempts: "Mission attempts",
        playtime: "Playing Time",
        dayspassed: "Days passed in game",
        safehouse: "Safehouse visits",
        rampages: "Rampages passed",
        hidden: "Hidden Packages found",
        youwasted: "People you've wasted",
        otherswasted: "People wasted by others",
        carsdestroyed: "Road Vehicles destroyed",
        boatsdestroyed: "Boats destroyed",
        aircraftdestroyed: "Planes & Helicopters destroyed",
        tires: "Tires popped with gunfire",
        starsattained: "Total number of wanted stars attained",
        starsevaded: "Total number of wanted stars evaded",
        busted: "Times busted",
        wasted: "Hospital visits",
        headshots: "Number of headshots",
        dailyspending: "Daily police spending",
        criminals: "Criminals wasted",
        explosives: "Kgs of explosives used",
        fired: "Bullets fired",
        hit: "Bullets hit",
        accuracy: "Accuracy",
        foot: "Dist. traveled on foot [miles]",
        car: "Dist. traveled by car [miles]",
        bike: "Dist. traveled by bike [miles]",
        boat: "Dist. traveled by boat [miles]",
        golf: "Dist. traveled by golf cart [miles]",
        heli: "Dist. traveled by helicopter [miles]",
        totaldistance: "Total distance traveled [miles]",
        maxdist: "Max. INSANE Jump dist. [m]",
        maxheight: "Max. INSANE Jump height. [m]",
        maxflip: "Max. INSANE Jump flips",
        unique: "Unique Jumps completed",
        maxrotation: "Max. INSANE Jump rotation",
        bestinsane: "Best INSANE stunt so far",
        noinsane: "No INSANE strunts completed",
        wheelietime: "Longest Wheelie time [secs]",
        wheeliedist: "Longest Wheelie distance [m]",
        stoppietime: "Longest Stoppie time [secs]",
        stoppiedist: "Longest Stoppie distance [m]",
        twowheeltime: "Longest 2 wheels time [secs]",
        twowheeldist: "Longest 2 wheels distance [m]",
        criminals_v: "Criminals killed on Vigilante Mission",
        vigilante: "Highest Vigilante Mission level",
        passengers: "Passengers dropped off",
        taxicash: "Cash made in taxi",
        peoplesaved: "People saved in an Ambulance",
        paramedic: "Highest Paramedic Mission level",
        fires: "Total fires extinguished",
        firetruck: "Fire Truck Mission level",
        stores: "Stores Knocked Off",
        assassination: "Assassination Contracts Completed",
        flight: "Flight hours",
        fish: "Fishes fed",
        mostfavorite: "Most Favorite Radio Station",
        leastfavorite: "Least Favorite Radio Station",
        sprayings: "Sprayings",
        weapon: "Weapon Budget",
        fashion: "Fashion Budget",
        property: "Property Budget",
        paynspray: "Auto Repair and Painting Budget",
        destroyed: "Property Destroyed",
        media: "Highest media attention",
        ignored: "Ignored",
        outof: " out of "
      }
    },
    pt: {
      menu: {
        map: "Mapa",
        brief: "Resumo",
        load: "Carregar",
        stats: "Estatísticas",
        controls: "Controles",
        audio: "Áudio",
        display: "Exibição",
        language: "Idioma",
        credits: "Créditos",
      },
      language: {
        english: "Inglês",
        french: "Francês",
        german: "Alemão",
        italian: "Italiano",
        spanish: "Espanhol",
      },
    },
    ru: {
      menu: {
        map: "Карта",
        brief: "Кратко",
        load: "Загрузить",
        stats: "Статистика",
        controls: "Управление",
        audio: "Аудио",
        display: "Дисплей",
        language: "Язык",
        credits: "Кредиты",
      },
      language: {
        english: "Английский",
        french: "Французский",
        german: "Немецкий",
        italian: "Итальянский",
        spanish: "Испанский",
      },
    },
  };
  
export const languageMap = {
    en: "en",
    fr: "fr",
    de: "de",
    it: "it",
    es: "es",
  };