export const menuStrings = {
    en: {
      menu: {
        map: "Map",
        brief: "Brief",
        load: "Load",
        stats: "Stats",
        controls: "Controls",
        audio: "Audio",
        display: "Display",
        language: "Language",
        credits: "Credits",
      },
      language: {
        english: "English",
        french: "French",
        german: "German",
        italian: "Italian",
        spanish: "Spanish",
      },
    },
    es: {
      menu: {
        map: "Mapa",
        brief: "Informe",
        load: "Cargar",
        stats: "Estadísticas",
        controls: "Controles",
        audio: "Sonido",
        display: "Pantalla",
        language: "Idioma",
        credits: "Créditos",
      },
      language: {
        english: "Inglés",
        french: "Francés",
        german: "Alemán",
        italian: "Italiano",
        spanish: "Español",
      },
    },
    fr: {
      menu: {
        map: "Carte",
        brief: "Briefing",
        load: "Charger",
        stats: "Statistiques",
        controls: "Commandes",
        audio: "Audio",
        display: "Affichage",
        language: "Langue",
        credits: "Crédits",
      },
      language: {
        english: "Anglais",
        french: "Français",
        german: "Allemand",
        italian: "Italien",
        spanish: "Espagnol",
      },
    },
    de: {
      menu: {
        map: "Karte",
        brief: "Missionsinfo",
        load: "Laden",
        stats: "Statistiken",
        controls: "Steuerung",
        audio: "Audio",
        display: "Anzeige",
        language: "Sprache",
        credits: "Credits",
      },
      language: {
        english: "Englisch",
        french: "Französisch",
        german: "Deutsch",
        italian: "Italienisch",
        spanish: "Spanisch",
      },
    },
    it: {
      menu: {
        map: "Mappa",
        brief: "Briefing",
        load: "Carica",
        stats: "Statistiche",
        controls: "Comandi",
        audio: "Audio",
        display: "Video",
        language: "Lingua",
        credits: "Crediti",
      },
      language: {
        english: "Inglese",
        french: "Francese",
        german: "Tedesco",
        italian: "Italiano",
        spanish: "Spagnolo",
      },
    },
    pt: {
      menu: {
        map: "Mapa",
        brief: "Resumo",
        load: "Carregar",
        stats: "Estatísticas",
        controls: "Controles",
        audio: "Áudio",
        display: "Exibição",
        language: "Idioma",
        credits: "Créditos",
      },
      language: {
        english: "Inglês",
        french: "Francês",
        german: "Alemão",
        italian: "Italiano",
        spanish: "Espanhol",
      },
    },
    ru: {
      menu: {
        map: "Карта",
        brief: "Кратко",
        load: "Загрузить",
        stats: "Статистика",
        controls: "Управление",
        audio: "Аудио",
        display: "Дисплей",
        language: "Язык",
        credits: "Кредиты",
      },
      language: {
        english: "Английский",
        french: "Французский",
        german: "Немецкий",
        italian: "Итальянский",
        spanish: "Испанский",
      },
    },
  };
  
export const languageMap = {
    en: "en",
    fr: "fr",
    de: "de",
    it: "it",
    es: "es",
  };